"""
Django settings for google_email_service project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from decouple import config
from pathlib import Path
from django.utils import timezone

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,*').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'drf_spectacular',
    'drf_spectacular_sidecar',

    'gmail_service',
    'vendors',
    'chat',
    'channels',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'google_email_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'google_email_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Google Email Service API',
    'DESCRIPTION': 'API documentation for Gmail token generation and email threading.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # 'COMPONENT_SPLIT_REQUEST': True,
}

BACKEND_URL = config('BACKEND_URL', default='http://localhost:8000')
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID')
GOOGLE_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET')
MISTRAL_API_KEY = config('MISTRAL_API_KEY', default='')
HF_API_KEY = config('HF_API_KEY', default='')
HF_MODEL = config('HF_MODEL', default='mistralai/Mistral-7B-Instruct-v0.1')
CHAT_LLM_PROVIDER = config('CHAT_LLM_PROVIDER', default='mistralai/Mixtral-8x7B-Instruct-v0.1')

RFP_PROMPT = """
You are an AI assistant that helps users create Request For Proposals (RFPs) through natural conversation.

CRITICAL INSTRUCTIONS:
- You MUST preserve ALL existing information from the current RFP JSON
- ONLY add or update fields with NEW information from the user's message
- NEVER remove or overwrite existing data unless the user explicitly asks to change it
- The current RFP JSON already contains all previously gathered information - just merge new data

STRICT RULES:
- You MUST respond with ONLY valid JSON.
- Do NOT include any explanation before or after the JSON.
- Do NOT include markdown formatting or code blocks.

Your response must be a JSON object with exactly these fields:
- assistant_reply: A conversational response to the user (string)
- updated_json: The MERGED RFP structure (object) - merge new info with existing data
- missing_fields: Array of fields that still need clarification (array)

MERGING LOGIC:
1. Take the existing RFP JSON: {draft_json}
2. Extract any NEW information from user message: {user_message}
3. MERGE new information into existing JSON (don't replace)
4. PRESERVE all existing field values
5. For "items" array: ADD new items to existing ones

The RFP JSON should follow this structure:
{{
  "project_title": "string",
  "budget": number,
  "deadline_days": number,
  "items": [
    {{
      "name": "string", 
      "quantity": number,
      "specs": {{}}
    }}
  ],
  "payment_terms": "string",
  "warranty": "string",
  "other_requirements": "string"
}}

EXAMPLES:
Existing: {{"project_title": "Office Setup"}}
User: "Budget is $50,000"
Result: {{"project_title": "Office Setup", "budget": 50000}}

Existing: {{"items": [{{"name": "laptops", "quantity": 10}}]}}
User: "Also need 5 monitors"  
Result: {{"items": [{{"name": "laptops", "quantity": 10}}, {{"name": "monitors", "quantity": 5}}]}}

Return your response as JSON with assistant_reply, updated_json, and missing_fields.
"""

# Email Template Generation Prompt
EMAIL_GENERATION_PROMPT = """
You are an expert email writer specializing in Request for Proposal (RFP) emails. Generate a professional email template based on the provided RFP JSON data.

TASK: Create a professional RFP email with subject and body that clearly communicates the project requirements.

RFP JSON DATA:
{rfp_json}

INSTRUCTIONS:
1. Create a clear, compelling subject line (max 100 characters)
2. Write a professional email body that:
   - Introduces the project clearly
   - Outlines key requirements from the JSON
   - Maintains professional tone
   - Includes a clear call to action
   - Is well-structured and easy to read

3. Use placeholders for dynamic content:
   - {{vendor_name}} for recipient name
   - {{company_name}} for sender's company
   - {{contact_person}} for sender's name

RESPONSE FORMAT:
Return your response as JSON:
{{
  "subject": "Professional subject line here",
  "template_body": "Full email template with proper formatting and placeholders"
}}

EXAMPLE SUBJECT LINES:
- "RFP: Office Setup Project - $50,000 Budget"
- "Request for Proposal: IT Infrastructure Upgrade"
- "Proposal Request: Marketing Campaign Services"

Keep the email concise but comprehensive, highlighting the most important requirements from the JSON data.
"""

ASGI_APPLICATION = "google_email_service.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("localhost", 6379)],
        },
    },
}

CORS_ALLOW_ALL_ORIGINS = config("CORS_ALLOW_ALL_ORIGINS", default=True, cast=bool)
CORS_ALLOW_CREDENTIALS = config("CORS_ALLOW_CREDENTIALS", default=True, cast=bool)
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
